### ISSUE TITLE
download deb file not work

### ISSUE THREAD

**Issue by zazu86** [megamaced/spotify-easyrpm#15] opened 2018-10-30 16:01 UTC
Hi,
the deb file download systematically fails
there is probably some problem with wget, at the end of the download the file disappears

I personally solved by editing the script and using curl in the f_download function

this is my function:
```
f_download() {
echo "Downloading the latest Spotify deb"
if ! curl "${V_HTTP_REPO}"/"${V_REPO_LATEST_DEB}" --output ${V_SOURCES_DIR}/${V_REPO_LATEST_DEB}; then
f_error "Failed to download Spotify. Aborting"
fi
}
```

my system:
openSUSE Leap 15.0
spotify-easyrpm 1.1.4-lp150.2.1

spotify downloaded:
spotify-client_1.0.92.390.g2ce5ec7d-18_amd64.deb

best regards
and thank you for the excellent work

**Comment by megamaced** [comment] 2018-11-09 22:45
hi I am unable to reproduce so far, I tested in Tumbleweed and SLE 15. But thanks for the nice curl alternative. If I get more reports of problems in the wild I will switch

**Comment by zazu86** [comment] 2019-02-15 13:01
Hello,
after the last updates of your script I tried to update spotify, but the problem has reoccurred again

I tried to better understand where the problem occurs,

so I focused on the file extraction function:

```
f_extract_deb() {
echo "Extracting deb and preparing"
ar -x "${V_SOURCES_DIR}"/"${V_PKGNAME}"*"${V_DEB_ARCH}".deb || f_error "Failed to extract deb"
rm control.tar.gz debian-binary
mv data.tar.gz "${V_SOURCES_DIR}"/
tar xzf "${V_SOURCES_DIR}"/data.tar.gz -C "${V_SOURCES_DIR}"/
mkdir -p "${V_SOURCES_DIR}"/"${V_PKGNAME}"
mv "${V_SOURCES_DIR}"/usr "${V_SOURCES_DIR}"/"${V_PKGNAME}"/
}
```

apparently, it seems as if the system is not able to figure out where it should extract files with ar

a simple trick was to insert a "cd" before extraction to move the job into the sources dir
```
f_extract_deb() {
echo "Extracting deb and preparing"
cd ${V_SOURCES_DIR}
ar -x "${V_SOURCES_DIR}"/"${V_PKGNAME}"*"${V_DEB_ARCH}".deb || f_error "Failed to extract deb"
rm control.tar.gz debian-binary
mv data.tar.gz "${V_SOURCES_DIR}"/
tar xzf "${V_SOURCES_DIR}"/data.tar.gz -C "${V_SOURCES_DIR}"/
mkdir -p "${V_SOURCES_DIR}"/"${V_PKGNAME}"
mv "${V_SOURCES_DIR}"/usr "${V_SOURCES_DIR}"/"${V_PKGNAME}"/
}
```

Unfortunately, due to lack of time I did not read the whole script accurately, I'm not sure that this small change could have affected other features, or cause abnormal behavior

**Comment by megamaced** [comment] 2019-02-24 00:02
I've been running from a clean openSUSE 15 vm, no modifications, and I can't replicate.

Can you edit the script and uncomment the # set -x at the top and try a build run using the original code. Should get some more verbose output which might give clues why its not working on your setup

**Comment by Bitti09** [comment] 2019-02-24 17:15
can't replicate this issue  on a clean Opensuse Tumbleweed installation

**Comment by megamaced** [comment] 2020-04-02 22:05
Closing as no further comments for over a year and can not reproduce

**Closed as completed by megamaced** 2020-04-02 22:05 UTC
Labels: Monitoring
